// host.ts: what harness/hostSide.ts needs to build THIS pack's firmware as
// a native host executable instead of a wasm32-freestanding module - the
// same real firmware sources build.ts compiles, minus the wasm-only linker
// flags (-nostdlib, --no-entry, --import-symbols, --export=), plus
// harness/host/driver.c (the native replay driver) and -DEMU_HOST_NATIVE=1
// (which unlocks emu_shim.c's own EMU_HOST_NATIVE block: two full-width
// pointer accessors driver.c needs - see that block's own comment for why
// emu_fb()/emu_device()'s (int)(intptr_t) truncation, harmless for
// wasm32's flat address space, is NOT safe on a native 64-bit host).
//
// A SIBLING FILE ON PURPOSE, NOT AN IMPORT OF build.ts: build.ts is a
// script that acts the moment it is run (parses argv, may already be
// compiling by the time an import finished), so importing it from here
// would either re-run a wasm build as a side effect of computing a host
// build's source list, or require restructuring build.ts's own proven
// path for a change this task does not ask for ("do not change what the
// existing wasm builds produce"). Trade-off taken deliberately: this file's
// SOURCES/INCLUDES/roster-generation are a second copy of build.ts's own
// (documented here as such, not hidden), kept only as far as the source
// LIST goes - the actual compiler invocation, retry policy and sanitizer
// flags live once, in harness/hostSide.ts, shared by every pack.
//
// EMU_EXPORTS below is this pack's own build.ts EMU_EXPORTS list, reused to
// derive -DEMU_HAS_<NAME>=1 defines: harness/host/driver.c calls every
// OPTIONAL emu_abi.h export (emu_sensor_vector, emu_app_current/switch,
// emu_menu_app_*, emu_arena_*) only when its matching guard is defined,
// mirroring the wasm side's "unimplemented means uncalled" contract
// (emu_abi.h) without needing weak symbols, whose support on a native
// COFF/PE target this repository has no reason to trust.
import { existsSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";

const WASM_DIR = import.meta.dir; // packs/rp2350-touch-amoled-18/wasm
const DEVICE_ROOT = resolve(WASM_DIR, ".."); // packs/rp2350-touch-amoled-18/
const REPO_ROOT = resolve(DEVICE_ROOT, "..", ".."); // the puck repo root
const FIRMWARE = join(DEVICE_ROOT, "firmware");
const ABI_DIR = join(REPO_ROOT, "wasm");

// Mirrors build.ts's own EMU_EXPORTS exactly (see that file for what each
// symbol is). Splitting mandatory (every build has these) from optional
// (guarded by -DEMU_HAS_*) matches emu_abi.h's own "core ABI" vs.
// "unimplemented means uncalled" split.
const OPTIONAL_EXPORTS = [
  "emu_sensor_vector",
  "emu_app_current",
  "emu_app_switch",
  "emu_menu_app_count",
  "emu_menu_app_index",
  "emu_arena_used",
  "emu_arena_capacity",
];

export interface HostAppArgs {
  appPath: string | null;
  landscape: boolean;
  shake: boolean;
}

export interface HostBuildFiles {
  sources: string[];
  includes: string[];
  defines: string[];
  // Call once building is done (success or failure) to remove the
  // generated app_roster.inc temp directory, if one was written.
  cleanup: () => void;
}

// Copied from build.ts's own generateRoster(), unchanged in shape (see that
// file for the full header comment on why a --app build needs a generated
// roster at all).
function generateRoster(appName: string, landscape: boolean, shake: boolean): { dir: string } {
  const dir = mkdtempSync(join(tmpdir(), "puck-host-roster-"));
  const rosterPath = join(dir, "app_roster.inc");
  const source = `// GENERATED by packs/rp2350-touch-amoled-18/wasm/host.ts. Not a pack
// firmware source: written to a temp file for one host build and deleted
// afterwards. See wasm/build.ts's own generateRoster() for the wasm twin
// of this file.
extern void port_enter(void);
extern void port_tick(const app_frame_t *f);

static const app_t g_portApp = { .name = "${appName}", .enter = port_enter, .tick = port_tick, .leave = NULL, .landscape = ${landscape ? "true" : "false"}, .wantsShake = ${shake ? "true" : "false"} };

const app_t *const g_apps[] = { &g_portApp };
const int g_appCount = 1;
const int g_menuAppIndex[] = { 0 };
const int g_menuAppCount = 1;
const app_t g_menuApp = { .name = "${appName}", .enter = port_enter, .tick = port_tick, .leave = NULL, .landscape = ${landscape ? "true" : "false"}, .wantsShake = ${shake ? "true" : "false"} };
void menu_set_return_app(int index) { (void)index; }

int sketch_tune_count(void) { return 0; }
bool sketch_tune_describe(int index, const char **name, float *min, float *max, float *def) {
    (void)index; (void)name; (void)min; (void)max; (void)def;
    return false;
}
const char *sketch_tune_define_name(int index) { (void)index; return NULL; }
bool sketch_tune_get(const char *name, float *out) { (void)name; (void)out; return false; }
bool sketch_tune_set(const char *name, float value, float *outApplied) {
    (void)name; (void)value; (void)outApplied;
    return false;
}
`;
  writeFileSync(rosterPath, source, "utf8");
  return { dir };
}

export function hostBuildFiles(args: HostAppArgs): HostBuildFiles {
  let rosterDir: string | null = null;
  if (args.appPath) {
    rosterDir = generateRoster(args.appPath.replace(/\.c$/, "").split(/[\\/]/).pop() ?? "port", args.landscape, args.shake).dir;
  }

  const RUNTIME_SOURCES = [
    join(WASM_DIR, "emu_shim.c"),
    join(FIRMWARE, "runtime", "runtime_core.c"),
    join(FIRMWARE, "runtime", "gfx.c"),
    join(FIRMWARE, "runtime", "tilt.c"),
    join(FIRMWARE, "runtime", "sound_synth.c"),
    join(FIRMWARE, "runtime", "tune_registry.c"),
  ];

  const sources = args.appPath
    ? [...RUNTIME_SOURCES, args.appPath]
    : [
        ...RUNTIME_SOURCES,
        join(FIRMWARE, "apps", "digits.c"),
        join(FIRMWARE, "apps", "chrono.c"),
        join(FIRMWARE, "apps", "sketch.c"),
        join(FIRMWARE, "apps", "menu.c"),
        join(FIRMWARE, "apps", "timer.c"),
        join(FIRMWARE, "apps", "shapes.c"),
      ];

  const includes = [
    ...(rosterDir ? [rosterDir] : []),
    join(WASM_DIR, "shim"),
    join(FIRMWARE, "runtime"),
    join(FIRMWARE, "apps"),
    ABI_DIR,
    ...(args.appPath ? [resolve(args.appPath, "..")] : []),
  ];

  const defines = ["-DSKETCH_LIVE_TUNE=1", "-DEMU_HOST_NATIVE=1", ...OPTIONAL_EXPORTS.map((name) => `-DEMU_HAS_${name.toUpperCase()}=1`)];

  for (const src of sources) {
    if (!existsSync(src)) throw new Error(`packs/rp2350-touch-amoled-18/wasm/host.ts: source not found: ${src}`);
  }

  const cleanup = () => {
    if (rosterDir) rmSync(rosterDir, { recursive: true, force: true });
  };

  return { sources, includes, defines, cleanup };
}
