// host.ts: what harness/hostSide.ts needs to build THIS pack's firmware as
// a native host executable instead of a wasm32-freestanding module. See
// packs/rp2350-touch-amoled-18/wasm/host.ts's header comment for the full
// reasoning shared by every pack's copy of this file (why a sibling to
// build.ts rather than an import of it, why -DEMU_HOST_NATIVE=1, why
// -DEMU_HAS_<NAME>=1 instead of weak symbols).
import { existsSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { basename, join, resolve } from "node:path";

const WASM_DIR = import.meta.dir; // packs/web/wasm
const PACK_ROOT = resolve(WASM_DIR, ".."); // packs/web
const REPO_ROOT = resolve(PACK_ROOT, "..", ".."); // the puck repo root
const RUNTIME = join(PACK_ROOT, "runtime");
const ABI_DIR = join(REPO_ROOT, "wasm");

// Mirrors wasm/build.ts's own EMU_EXPORTS. Mandatory ones (emu_device,
// emu_init, emu_tick, emu_fb, emu_push_*, emu_touch, emu_button,
// emu_button_verdict, emu_sensor_event) are always called by
// harness/host/driver.c with no guard; these three are the ones build.ts
// exports beyond that baseline.
const OPTIONAL_EXPORTS = ["emu_sensor_vector", "emu_app_current", "emu_app_switch"];

export interface HostAppArgs {
  appPath: string | null;
  landscape: boolean;
  shake: boolean;
}

export interface HostBuildFiles {
  sources: string[];
  includes: string[];
  defines: string[];
  cleanup: () => void;
}

// Mirrors wasm/build.ts's own generateRoster(): one app_t built around a
// port's port_enter()/port_tick(), for the pack's single g_webApp slot.
function generateRoster(appName: string, landscape: boolean, shake: boolean): string {
  const dir = mkdtempSync(join(tmpdir(), "puck-host-web-roster-"));
  const rosterPath = join(dir, "roster.c");
  const source = `// GENERATED by packs/web/wasm/host.ts. Not a pack firmware source: written
// to a temp file for one host build and deleted afterwards. See
// wasm/build.ts's own generateRoster() for the wasm twin of this file.
#include <stdbool.h>
#include <stddef.h>
#include "app.h"

extern void port_enter(void);
extern void port_tick(const app_frame_t *f);

const app_t g_webApp = {
    .name       = "${appName}",
    .enter      = port_enter,
    .tick       = port_tick,
    .leave      = NULL,
    .landscape  = ${landscape ? "true" : "false"},
    .wantsShake = ${shake ? "true" : "false"},
};
`;
  writeFileSync(rosterPath, source, "utf8");
  return rosterPath;
}

export function hostBuildFiles(args: HostAppArgs): HostBuildFiles {
  let rosterDir: string | null = null;
  let rosterFile: string | null = null;
  if (args.appPath) {
    rosterFile = generateRoster(basename(args.appPath).replace(/\.c$/, ""), args.landscape, args.shake);
    rosterDir = resolve(rosterFile, "..");
  }

  const sources = [
    join(WASM_DIR, "emu_shim.c"),
    join(RUNTIME, "runtime_core.c"),
    join(RUNTIME, "gfx.c"),
    join(RUNTIME, "digits.c"),
    ...(args.appPath ? [args.appPath, rosterFile!] : [join(PACK_ROOT, "apps", "demo.c")]),
  ];

  const includes = [join(WASM_DIR, "shim"), RUNTIME, ABI_DIR, ...(args.appPath ? [resolve(args.appPath, "..")] : [])];

  const defines = ["-DEMU_HOST_NATIVE=1", ...OPTIONAL_EXPORTS.map((name) => `-DEMU_HAS_${name.toUpperCase()}=1`)];

  for (const src of sources) {
    if (!existsSync(src)) throw new Error(`packs/web/wasm/host.ts: source not found: ${src}`);
  }

  const cleanup = () => {
    if (rosterDir) rmSync(rosterDir, { recursive: true, force: true });
  };

  return { sources, includes, defines, cleanup };
}
