/*
 * harness/host/driver.c: the native-host replacement for "the browser page
 * that drives a wasm module" (src/wasm.ts + src/replayCore.ts), for the
 * third harness side (harness/hostSide.ts, docs/harness.md's "three marks").
 *
 * WHY THIS IS C, IN A REPOSITORY THAT IS OTHERWISE TYPESCRIPT-ONLY
 * (AGENTS.md): it links directly against real firmware object code (the
 * same sources a pack's wasm/build.ts compiles - see each pack's own
 * wasm/host.ts), in the SAME executable, so the compiler that builds THIS
 * file is the compiler under test. A TypeScript driver could not call
 * emu_tick() by C linkage; it would need a second boundary (an FFI, a
 * socket, another process), and that boundary is exactly the kind of
 * seam-in-the-wrong-place decision 0008 already warns against for the
 * hardware link. Keep this file minimal: everything that can live in
 * harness/hostSide.ts (the trace-driving policy, capture-point selection,
 * the subprocess protocol, sanitizer-report detection) does.
 *
 * WHAT THIS FILE DOES: reads a simple line-based protocol on stdin (one
 * trace-event-shaped command per line, written by harness/hostSide.ts in
 * the exact order src/replayCore.ts's replayFromBytes() already replays a
 * trace in), calls the matching emu_abi.h export, and on a CAPTURE command
 * writes the current framebuffer to stdout as `FRAME <atMs> <w> <h>\n`
 * followed by exactly w*h*3 raw RGB bytes (row-major, top-left origin - the
 * same CapturedFrame shape harness/types.ts documents, so hostSide.ts needs
 * no format-specific knowledge to read this back).
 *
 * DEVICE-AGNOSTIC, same rule AGENTS.md states for src/ and harness/: no
 * panel size, no button name, anywhere below. The panel's width, height and
 * pixel format come from calling the firmware's own emu_device() and
 * reading its JSON, exactly like src/wasm.ts's readDeviceDescriptor() does
 * - this file just does the JSON reading itself, in C, since there is no
 * JS runtime here to hand the string to. Pixel conversion mirrors
 * src/panel.ts's PIXEL_READERS exactly (same two formats, same bit-
 * replication expansion) so a host frame and a wasm frame are byte-for-byte
 * comparable by harness/hostdiff.ts's plain compareFrames() call, with no
 * format-specific fudge on either side.
 *
 * THE POINTER-WIDTH PROBLEM THIS FILE DOES NOT SOLVE ITSELF: emu_fb() and
 * emu_device() are both declared `int` by wasm/emu_abi.h, correct for a
 * wasm32 module's flat address space but not safe to trust on a native
 * 64-bit host (this process's own static/heap data commonly sits above
 * 4GB). This file calls emu_init()/emu_device() for their real job (bring
 * the firmware up, build its device JSON) but reads the actual pointers
 * back through emu_fb_native()/emu_device_json_native() - two small,
 * additive, EMU_HOST_NATIVE-guarded accessors each pack's own emu_shim.c
 * carries for exactly this reason (see e.g.
 * packs/rp2350-touch-amoled-18/wasm/emu_shim.c's own copy of this
 * comment). Every pack this file is built against must supply both; a pack
 * with neither cannot be host-built, by construction, and the link fails
 * loudly rather than silently misreading a truncated pointer.
 *
 * OPTIONAL emu_abi.h EXPORTS (emu_sensor_vector, emu_accel_sample): called
 * only when the pack's own wasm/host.ts defined the matching
 * -DEMU_HAS_<NAME>=1, mirroring emu_abi.h's "unimplemented means uncalled"
 * contract without relying on weak symbols, whose support on a native
 * COFF/PE target (this repository is developed on Windows) this file has
 * no reason to trust untested.
 */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "emu_abi.h"

/* ---- the two EMU_HOST_NATIVE accessors every host-buildable pack's
 * emu_shim.c supplies - see this file's header comment. Declared here, not
 * in emu_abi.h: they are not part of the wasm ABI, only of this native
 * driver's own contract with a pack's shim. */
extern void *emu_fb_native(void);
extern const char *emu_device_json_native(void);

/* ---- js_log: the one thing every emu_shim.c imports from "the host".
 * The wasm side's host is the browser console pane (src/consolelog.ts);
 * this driver's host is this process's own stderr, so a firmware log line
 * lands next to a sanitizer report rather than being lost. */
void js_log(const char *ptr, int len) {
    if (len > 0) fwrite(ptr, 1, (size_t)len, stderr);
    fputc('\n', stderr);
}

/* ===========================================================================
 * A tiny, deliberately non-general JSON reader for emu_device()'s output.
 * Not a JSON PARSER: emu_device() is generated by trusted pack C (see e.g.
 * packs/rp2350-touch-amoled-18/wasm/emu_shim.c's json_append helpers), in a
 * known, flat shape, so this only ever needs to find one `"key":value` or
 * `"key":"value"` pair at a time textually - the same trade a real JSON
 * parser would be overkill for, made explicitly rather than silently
 * assumed.
 * ======================================================================= */

/* Finds `"key":` then reads the (possibly negative) integer that follows.
 * Returns 1 on success, 0 if the key was not found or was not followed by
 * a number. */
static int find_int_field(const char *json, const char *key, int *out) {
    const char *p = strstr(json, key);
    if (!p) return 0;
    p += strlen(key);
    while (*p == ' ') p++;
    char *end = NULL;
    long v = strtol(p, &end, 10);
    if (end == p) return 0;
    *out = (int)v;
    return 1;
}

/* Finds `"key":"` then copies characters up to the closing quote into out
 * (NUL-terminated, truncated to outCap-1 if needed - every value this file
 * actually reads, "rgb565be"/"rgb565", is far shorter than any reasonable
 * outCap). Returns 1 on success, 0 if the key was not found. */
static int find_str_field(const char *json, const char *key, char *out, size_t outCap) {
    const char *p = strstr(json, key);
    if (!p) return 0;
    p += strlen(key);
    size_t n = 0;
    while (*p && *p != '"' && n + 1 < outCap) out[n++] = *p++;
    out[n] = '\0';
    return 1;
}

/* ===========================================================================
 * Pixel conversion, mirroring src/panel.ts's PIXEL_READERS exactly (same
 * two formats, same bit-replication expansion) so a captured host frame is
 * byte-for-byte comparable against a captured wasm frame with no
 * format-specific tolerance on either side.
 * ======================================================================= */
typedef void (*pixel_reader_t)(uint16_t raw, uint8_t *r, uint8_t *g, uint8_t *b);

/* "rgb565be": the framebuffer holds RGB565 with its two bytes in the panel
 * DMA's order, the opposite of a native uint16_t's byte order on every
 * little-endian target this repository builds for - see src/panel.ts's own
 * rgb565be() for the identical unswap-then-expand this mirrors. */
static void rgb565be_reader(uint16_t raw, uint8_t *r, uint8_t *g, uint8_t *b) {
    uint16_t v = (uint16_t)(((raw & 0xffu) << 8) | ((raw >> 8) & 0xffu));
    uint8_t r5 = (uint8_t)((v >> 11) & 0x1fu);
    uint8_t g6 = (uint8_t)((v >> 5) & 0x3fu);
    uint8_t b5 = (uint8_t)(v & 0x1fu);
    *r = (uint8_t)((r5 << 3) | (r5 >> 2));
    *g = (uint8_t)((g6 << 2) | (g6 >> 4));
    *b = (uint8_t)((b5 << 3) | (b5 >> 2));
}

/* "rgb565": a plain little-endian RGB565 reader, no byte swap - see
 * src/panel.ts's own rgb565(). */
static void rgb565_reader(uint16_t raw, uint8_t *r, uint8_t *g, uint8_t *b) {
    uint8_t r5 = (uint8_t)((raw >> 11) & 0x1fu);
    uint8_t g6 = (uint8_t)((raw >> 5) & 0x3fu);
    uint8_t b5 = (uint8_t)(raw & 0x1fu);
    *r = (uint8_t)((r5 << 3) | (r5 >> 2));
    *g = (uint8_t)((g6 << 2) | (g6 >> 4));
    *b = (uint8_t)((b5 << 3) | (b5 >> 2));
}

static pixel_reader_t pixel_reader_for(const char *format) {
    if (strcmp(format, "rgb565be") == 0) return rgb565be_reader;
    if (strcmp(format, "rgb565") == 0) return rgb565_reader;
    return NULL;
}

/* Generous, static (no dependency on a pack's own bump-allocator heap
 * budget - see this file's header comment on why this driver stays out of
 * a pack's malloc() entirely): no panel this ecosystem is expected to
 * emulate is anywhere near this wide. Checked at runtime below, not
 * silently truncated. */
#define MAX_PANEL_W 4096
static uint8_t g_row[MAX_PANEL_W * 3];

static void capture_frame(long atMs, int panelW, int panelH, pixel_reader_t reader) {
    const uint16_t *fb = (const uint16_t *)emu_fb_native();
    /* fprintf(stdout, ...), never bare printf(): a pack's own emu_shim.c
     * defines its OWN global `int printf(const char *fmt, ...)` (a small
     * format-subset firmware logger that ends in rt_log()/js_log(), i.e.
     * THIS driver's own stderr - see e.g.
     * packs/rp2350-touch-amoled-18/wasm/emu_shim.c's "printf" section), and
     * a pack's own firmware sources are compiled with that pack's shim/
     * directory on their include path, which declares printf as a PLAIN
     * extern (no dllimport) - so their calls bind directly to emu_shim.c's
     * own definition, exactly as intended for real firmware logging.
     * `fprintf`/`fwrite`/`fputc` are never touched by any pack's shim
     * (only bare `printf` is), so using them here is what keeps this
     * FRAME header landing on the real stdout instead of being silently
     * rerouted through a pack's own logger - found by actually running
     * this against real pack firmware and watching the header vanish from
     * stdout, not assumed. */
    fprintf(stdout, "FRAME %ld %d %d\n", atMs, panelW, panelH);
    fflush(stdout);
    for (int y = 0; y < panelH; y++) {
        const uint16_t *rowFb = fb + (size_t)y * (size_t)panelW;
        int di = 0;
        for (int x = 0; x < panelW; x++) {
            uint8_t r, g, b;
            reader(rowFb[x], &r, &g, &b);
            g_row[di++] = r;
            g_row[di++] = g;
            g_row[di++] = b;
        }
        fwrite(g_row, 1, (size_t)panelW * 3, stdout);
    }
    fflush(stdout);
}

/* Strips a trailing \n and/or \r (this protocol may cross a Windows/Unix
 * line-ending boundary depending on how harness/hostSide.ts's own child
 * process pipe behaves). */
static void chomp(char *s) {
    size_t n = strlen(s);
    while (n > 0 && (s[n - 1] == '\n' || s[n - 1] == '\r')) s[--n] = '\0';
}

int main(void) {
    if (emu_init() == 0) {
        fprintf(stderr, "harness/host/driver.c: emu_init() returned 0\n");
        return 1;
    }

    (void)emu_device(); /* return value is a truncated pointer on a native
                          * host (see this file's header comment) - only
                          * its SIDE EFFECT (building the device JSON
                          * buffer) matters here; the real pointer comes
                          * from emu_device_json_native() below. */
    const char *deviceJson = emu_device_json_native();

    int panelW = 0, panelH = 0;
    char format[32];
    if (!find_int_field(deviceJson, "\"w\":", &panelW) || !find_int_field(deviceJson, "\"h\":", &panelH) ||
        !find_str_field(deviceJson, "\"format\":\"", format, sizeof format)) {
        fprintf(stderr, "harness/host/driver.c: could not read panel w/h/format from emu_device()'s JSON: %s\n", deviceJson);
        return 1;
    }
    if (panelW <= 0 || panelH <= 0 || panelW > MAX_PANEL_W) {
        fprintf(stderr, "harness/host/driver.c: implausible panel size %dx%d from emu_device()\n", panelW, panelH);
        return 1;
    }
    pixel_reader_t reader = pixel_reader_for(format);
    if (!reader) {
        fprintf(stderr, "harness/host/driver.c: unsupported panel pixel format \"%s\" (this driver implements: rgb565be, rgb565)\n", format);
        return 1;
    }

    char line[256];
    while (fgets(line, sizeof line, stdin)) {
        chomp(line);
        if (line[0] == '\0') continue;

        if (strncmp(line, "TICK ", 5) == 0) {
            unsigned long nowMs = 0;
            if (sscanf(line + 5, "%lu", &nowMs) != 1) goto bad_line;
            emu_tick((uint32_t)nowMs);
        } else if (strncmp(line, "TOUCH ", 6) == 0) {
            int down = 0, x = 0, y = 0;
            if (sscanf(line + 6, "%d %d %d", &down, &x, &y) != 3) goto bad_line;
            emu_touch(down, x, y);
        } else if (strncmp(line, "BUTTON ", 7) == 0) {
            int index = 0, down = 0;
            if (sscanf(line + 7, "%d %d", &index, &down) != 2) goto bad_line;
            emu_button(index, down);
        } else if (strncmp(line, "VERDICT ", 8) == 0) {
            int index = 0, isLong = 0;
            if (sscanf(line + 8, "%d %d", &index, &isLong) != 2) goto bad_line;
            emu_button_verdict(index, isLong);
        } else if (strncmp(line, "SENSOR ", 7) == 0) {
            int index = 0;
            if (sscanf(line + 7, "%d", &index) != 1) goto bad_line;
            emu_sensor_event(index);
        } else if (strncmp(line, "VECTOR ", 7) == 0) {
            int index = 0;
            float x = 0, y = 0, z = 0;
            if (sscanf(line + 7, "%d %f %f %f", &index, &x, &y, &z) != 4) goto bad_line;
#ifdef EMU_HAS_EMU_SENSOR_VECTOR
            emu_sensor_vector(index, x, y, z);
#endif
        } else if (strncmp(line, "ACCEL ", 6) == 0) {
            int index = 0;
            unsigned long tMs = 0;
            float ax = 0, ay = 0, az = 0;
            if (sscanf(line + 6, "%d %lu %f %f %f", &index, &tMs, &ax, &ay, &az) != 5) goto bad_line;
#ifdef EMU_HAS_EMU_ACCEL_SAMPLE
            emu_accel_sample(index, (uint32_t)tMs, ax, ay, az);
#endif
        } else if (strncmp(line, "CAPTURE ", 8) == 0) {
            long atMs = 0;
            if (sscanf(line + 8, "%ld", &atMs) != 1) goto bad_line;
            capture_frame(atMs, panelW, panelH, reader);
        } else if (strcmp(line, "END") == 0) {
            break;
        } else {
            goto bad_line;
        }
        continue;

    bad_line:
        fprintf(stderr, "harness/host/driver.c: malformed protocol line: \"%s\"\n", line);
        return 1;
    }

    return 0;
}
